In [241]:
import pandas as pd
from tqdm import tqdm

In [242]:
def augustus_refs(df):
    out_df= pd.DataFrame()
    accessions=df["accession"].unique().tolist()
    for acc in accessions:    
        busco = pd.read_csv(f"/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/sqanti/ref_genes/augustus_mappings/busco_{acc}.txt", header=None)
        house = pd.read_csv(f"/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/sqanti/ref_genes/augustus_mappings/housekeeping_{acc}.txt", header=None)
        nlr = pd.read_csv(f"/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/sqanti/ref_genes/augustus_mappings/nlrs_{acc}.txt", header=None)

        busco["type"] = "busco"
        house["type"] = "housekeeping"
        nlr["type"] = "nlr"
        gene_type = pd.concat([busco,house,nlr])
        gene_type.columns = ["ref_isoform","type"]
        gene_type = gene_type.groupby("ref_isoform")["type"].apply(', '.join).reset_index()

        gene_type["ref_gene"] = gene_type["ref_isoform"].str.split(".").str[0]
        gene_type.loc[gene_type["type"] == "busco, nlr"] = "nlr"
        gene_type.loc[gene_type["type"] == "housekeeping, nlr"] = "nlr"
        gene_type.loc[gene_type["type"] == "busco, housekeeping"] = "housekeeping"

        sub=df.loc[df["accession"]==acc]
        sub = pd.merge(left=sub, right=gene_type, how='left', left_on='associated_gene', right_on='ref_gene')
        
        out_df=pd.concat([out_df,sub])
    return out_df

### Prepare the mapping of gene type to Sqanti gene

In [245]:
# full df
aug_ref=pd.read_pickle("pb_augustus_sqanti_full.pkl")
aug_map=aug_ref[["accession","gene","associated_gene","isoform","gene_read_support"]]
aug_map["association"] = aug_map["associated_gene"].str.split("_").str.len().copy()
# split by clear cases and different ones
clear = aug_map.loc[aug_map["association"] == 1]
unclear = aug_map.loc[aug_map["association"] != 1]
# remove duplicated TAMA genes (still keeps the rows with more than one reference gene association)
clear_genes=clear.drop(labels="isoform", axis=1).drop_duplicates()
# associate gene type
#IDs = augustus_refs(clear_genes)

/tmp/ipykernel_125067/602736232.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aug_map["association"] = aug_map["associated_gene"].str.split("_").str.len().copy()

### Real analysis (for accession)

In [246]:
# get associated genes
geneID=clear.loc[clear["accession"]=="at9900"]

In [247]:
geneID

,accession,gene,associated_gene,isoform,gene_read_support,association
0,at9900,PB.1,g2,PB.1.1,2,1
1,at9900,PB.1,g2,PB.1.2,2,1
2,at9900,PB.10,g12,PB.10.1,96,1
3,at9900,PB.10,g12,PB.10.10,96,1
4,at9900,PB.10,g12,PB.10.11,96,1
...,...,...,...,...,...,...
325924,at9900,PB.16856,g31817,PB.16856.8,35,1
325925,at9900,PB.16856,g31817,PB.16856.9,35,1
325926,at9900,PB.16857,g31818,PB.16857.1,7,1
325927,at9900,PB.16857,g31818,PB.16857.2,7,1
325928,at9900,PB.16857,g31818,PB.16857.3,7,1

In [248]:
# get gene ID, present ore than once
x=geneID["gene"].value_counts() > 1
x=x.reset_index()
x.columns=["gene", "bool"]
dups=x.loc[x["bool"]==True,"gene"].tolist()

In [249]:
# get the genes from the clear dataframe
unclear_cans=geneID[geneID["gene"].isin(dups)]

In [250]:
unclear_cans

,accession,gene,associated_gene,isoform,gene_read_support,association
0,at9900,PB.1,g2,PB.1.1,2,1
1,at9900,PB.1,g2,PB.1.2,2,1
2,at9900,PB.10,g12,PB.10.1,96,1
3,at9900,PB.10,g12,PB.10.10,96,1
4,at9900,PB.10,g12,PB.10.11,96,1
...,...,...,...,...,...,...
325924,at9900,PB.16856,g31817,PB.16856.8,35,1
325925,at9900,PB.16856,g31817,PB.16856.9,35,1
325926,at9900,PB.16857,g31818,PB.16857.1,7,1
325927,at9900,PB.16857,g31818,PB.16857.2,7,1
325928,at9900,PB.16857,g31818,PB.16857.3,7,1

In [ ]:
# add type to already unclear

In [210]:
## move them to the unclear list
unclear_acc = unclear.loc[unclear["accession"]=="at9900"]
unclear_fin = pd.concat([unclear_acc,unclear_cans])

,accession,gene,associated_gene,isoform,gene_read_support,association
227,at9900,PB.1008,novelGene_14,PB.1008.1,1,2
403,at9900,PB.1014,novelGene_15,PB.1014.7,23,2
507,at9900,PB.102,g132_g131,PB.102.24,96,2
518,at9900,PB.102,g132_g131,PB.102.34,96,2
737,at9900,PB.1034,novelGene_g1472_AS,PB.1034.1,1,3
...,...,...,...,...,...,...
325766,at9900,PB.16846,novelGene_1278,PB.16846.8,17,2
325767,at9900,PB.16846,novelGene_1279,PB.16846.9,17,2
325867,at9900,PB.16849,g31801_g31802,PB.16849.1,18,2
325898,at9900,PB.16853,g31812_g31811,PB.16853.1,4,2
325900,at9900,PB.16853,g31812_g31811,PB.16853.3,4,2

In [162]:
geneID[geneID["gene"] == "PB.4434"]

,accession,gene,associated_gene,gene_read_support,association,ref_isoform,type,ref_gene
4290,at9900,PB.4434,g7783,1139,1,NaN,NaN,NaN
4291,at9900,PB.4434,g7781,1139,1,NaN,NaN,NaN
4292,at9900,PB.4434,g7786,1139,1,NaN,NaN,NaN
4293,at9900,PB.4434,g7789,1139,1,NaN,NaN,NaN
4294,at9900,PB.4434,g7791,1139,1,NaN,NaN,NaN

In [78]:
# load orf df
at9900=pd.read_pickle("sqanti/at9900_pb_augustus_sqanti_orf.pkl")

In [79]:
at9900

,Gene,n ORFs,n Isoforms,Sqanti ORFs,Isoforms,n_Isoforms_ORF,Subcategories,Read_Support,Read_Support_ORF
0,PB.1,0,0,[],[],[],[],[],[]
0,PB.10,16,33,[MERTNSIEMDRERLTAEMAFRDSSSAVIRIRRRLPDLLTSVKLKY...,"[[PB.10.1, PB.10.10, PB.10.12, PB.10.13, PB.10...","[12, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]","[[mono-exon, mono-exon, mono-exon, mono-exon, ...","[[3, 5, 1, 19, 1, 22, 1, 16, 1, 1, 1, 4], [1, ...","[75, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
0,PB.100,11,17,[MATKPGVLTDWPWTPLGSFKYIVIAPWAVHSTYRFVTDDPEKRDL...,"[[PB.100.1, PB.100.16, PB.100.3, PB.100.6, PB....","[5, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]","[[alternative_3end5end, alternative_3end, alte...","[[1, 1, 10, 1, 3], [1, 1], [1, 1], [1], [1], [...","[16, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]"
0,PB.1000,9,14,[MEGMLSSGDQQRLVSSFLEIAVGQTAETARQFLQATSWKLEEAIQ...,"[[PB.1000.1, PB.1000.2, PB.1000.3, PB.1000.4, ...","[5, 2, 1, 1, 1, 1, 1, 1, 1]","[[at_least_one_novel_splicesite, at_least_one_...","[[4, 12, 3, 2, 1], [1, 1], [1], [1], [1], [1],...","[22, 2, 1, 1, 1, 1, 1, 1, 1]"
0,PB.10000,1,1,[MLLDCWAIPCVLVLTWFYLKTKYRLMKISGVFICIVGVFMVVFSD...,[[PB.10000.1]],[1],[[intron_retention]],[[1]],[1]
...,...,...,...,...,...,...,...,...,...
0,PB.9995,1,5,[MEANKKAKPSYGDVISNLPNDLLCRILSYLSTKEAALTSILSKRW...,"[[PB.9995.1, PB.9995.2, PB.9995.3, PB.9995.4, ...",[5],"[[alternative_3end5end, alternative_3end5end, ...","[[1, 1, 1, 1, 1]]",[5]
0,PB.9996,5,5,[MAANVDNPQVSTLKLILVYLLIGLCSVLCLMVRSVCVVIMCMKSS...,"[[PB.9996.1], [PB.9996.2], [PB.9996.3], [PB.99...","[1, 1, 1, 1, 1]","[[at_least_one_novel_splicesite], [alternative...","[[1], [1], [1], [1], [1]]","[1, 1, 1, 1, 1]"
0,PB.9997,8,27,[MDDCSKDLINCLPDNLLCQILSNLSTKEAALTSLLSKRWRYLFAL...,"[[PB.9997.1, PB.9997.10, PB.9997.11, PB.9997.1...","[19, 2, 1, 1, 1, 1, 1, 1]","[[at_least_one_novel_splicesite, alternative_3...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,...","[20, 2, 1, 1, 1, 1, 1, 1]"
0,PB.9998,9,19,[MKKAFGQTVRDLKRGVNKKVLKVPGIEQKVLDATSNESWGPHGSL...,"[[PB.9998.10, PB.9998.12, PB.9998.13, PB.9998....","[10, 2, 1, 1, 1, 1, 1, 1, 1]","[[at_least_one_novel_splicesite, at_least_one_...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1], [1], ...","[10, 2, 1, 1, 1, 1, 1, 1, 1]"
0,PB.9999,2,3,[MAGRLLANLIVMGSGIIGRAVFQAYRQALANASKSGVAQEAMQNG...,"[[PB.9999.2, PB.9999.3], [PB.9999.1]]","[2, 1]","[[alternative_3end5end, alternative_3end5end],...","[[1, 1], [1]]","[2, 1]"

In [20]:
# merge the type to the df
at9900_type=pd.merge(left=at9900, right=geneID[["gene","accession","associated_gene","type"]], how='left', left_on='Gene', right_on='gene').drop(labels="gene", axis=1)

### Read support for each sqanti gene

In [22]:
nlr = at9900_type.loc[at9900_type["type"]=="nlr"]
busco = at9900_type.loc[at9900_type["type"]=="busco"]
house= at9900_type.loc[at9900_type["type"]=="housekeeping"]

In [24]:
nlr["Gene"].value_counts()

PB.11213    2
PB.10722    1
PB.2936     1
PB.3271     1
PB.3265     1
           ..
PB.14957    1
PB.14956    1
PB.14895    1
PB.14871    1
PB.9420     1
Name: Gene, Length: 123, dtype: int64

In [183]:
nlr["n ORFs"].mean()

8.838709677419354

In [184]:
busco["n ORFs"].mean()

8.545280960174578

In [185]:
house["n ORFs"].mean()

6.261006289308176

In [186]:
at9900_type["n ORFs"].mean()

8.551459024986896

In [188]:
nlr["n Isoforms"].mean()

15.274193548387096

In [189]:
busco["n Isoforms"].mean()

18.222858701582105

In [190]:
house["n Isoforms"].mean()

13.515723270440251

In [191]:
at9900_type["n Isoforms"].mean()

19.29599860213175

In [211]:
for i in range(len(at9900_type)):
    if len(at9900_type.iloc[i]["Isoforms"]) == 0:
        continue
    else:
        for orf in at9900_type.iloc[i]["Isoforms"]:
            print(orf)
    #print(len(at9900_type.iloc[i]["Isoforms"]))

hi
['PB.10.1', 'PB.10.10', 'PB.10.12', 'PB.10.13', 'PB.10.14', 'PB.10.21', 'PB.10.25', 'PB.10.28', 'PB.10.3', 'PB.10.32', 'PB.10.33', 'PB.10.5']
['PB.10.11', 'PB.10.22', 'PB.10.30']
['PB.10.16', 'PB.10.19']
['PB.10.17', 'PB.10.24']
['PB.10.18', 'PB.10.31']
['PB.10.26', 'PB.10.8']
['PB.10.15']
['PB.10.2']
['PB.10.20']
['PB.10.23']
['PB.10.27']
['PB.10.29']
['PB.10.4']
['PB.10.6']
['PB.10.7']
['PB.10.9']
['PB.100.1', 'PB.100.16', 'PB.100.3', 'PB.100.6', 'PB.100.7']
['PB.100.10', 'PB.100.14']
['PB.100.11', 'PB.100.2']
['PB.100.12']
['PB.100.13']
['PB.100.15']
['PB.100.17']
['PB.100.4']
['PB.100.5']
['PB.100.8']
['PB.100.9']
['PB.1000.1', 'PB.1000.2', 'PB.1000.3', 'PB.1000.4', 'PB.1000.6']
['PB.1000.5', 'PB.1000.8']
['PB.1000.10']
['PB.1000.11']
['PB.1000.12']
['PB.1000.13']
['PB.1000.14']
['PB.1000.7']
['PB.1000.9']
['PB.10000.1']
['PB.10001.1', 'PB.10001.10', 'PB.10001.11', 'PB.10001.12', 'PB.10001.17', 'PB.10001.18', 'PB.10001.2', 'PB.10001.26', 'PB.10001.5', 'PB.10001.7', 'PB.10001.9']
['PB.10001.13', 'PB.10001.14', 'PB.10001.16', 'PB.10001.20', 'PB.10001.21', 'PB.10001.29']
['PB.10001.23', 'PB.10001.4']
['PB.10001.15']
['PB.10001.19']
['PB.10001.22']
['PB.10001.24']
['PB.10001.25']
['PB.10001.27']
['PB.10001.28']
['PB.10001.3']
['PB.10001.30']
['PB.10001.6']
['PB.10001.8']
['PB.10002.1']
['PB.10002.2']
['PB.10002.3']
['PB.10002.4']
['PB.10002.5']
['PB.10003.1', 'PB.10003.10', 'PB.10003.13', 'PB.10003.17', 'PB.10003.2', 'PB.10003.20', 'PB.10003.21', 'PB.10003.23', 'PB.10003.24', 'PB.10003.25', 'PB.10003.26', 'PB.10003.27', 'PB.10003.29', 'PB.10003.3', 'PB.10003.31', 'PB.10003.4', 'PB.10003.5', 'PB.10003.6', 'PB.10003.7', 'PB.10003.8', 'PB.10003.9']
['PB.10003.33', 'PB.10003.34', 'PB.10003.35', 'PB.10003.36', 'PB.10003.37', 'PB.10003.38', 'PB.10003.39', 'PB.10003.40', 'PB.10003.41', 'PB.10003.42', 'PB.10003.43', 'PB.10003.44']
['PB.10003.11', 'PB.10003.12', 'PB.10003.14', 'PB.10003.28', 'PB.10003.45', 'PB.10003.46']
['PB.10003.19', 'PB.10003.22']
['PB.10003.15']
['PB.10003.16']
['PB.10003.18']
['PB.10003.30']
['PB.10003.32']
['PB.10004.1', 'PB.10004.2']
['PB.10004.3']
['PB.10005.1', 'PB.10005.11', 'PB.10005.12', 'PB.10005.13', 'PB.10005.15', 'PB.10005.17', 'PB.10005.19', 'PB.10005.2', 'PB.10005.20', 'PB.10005.21', 'PB.10005.22', 'PB.10005.23', 'PB.10005.24', 'PB.10005.25', 'PB.10005.26', 'PB.10005.27', 'PB.10005.29', 'PB.10005.3', 'PB.10005.33', 'PB.10005.35', 'PB.10005.4', 'PB.10005.6', 'PB.10005.7', 'PB.10005.8', 'PB.10005.9']
['PB.10005.10']
['PB.10005.14']
['PB.10005.16']
['PB.10005.18']
['PB.10005.28']
['PB.10005.30']
['PB.10005.31']
['PB.10005.32']
['PB.10005.34']
['PB.10005.5']
['PB.10006.1']
['PB.10007.10', 'PB.10007.11', 'PB.10007.12', 'PB.10007.13', 'PB.10007.14', 'PB.10007.16', 'PB.10007.17', 'PB.10007.3', 'PB.10007.4', 'PB.10007.5', 'PB.10007.6', 'PB.10007.7', 'PB.10007.8', 'PB.10007.9']
['PB.10007.1']
['PB.10007.15']
['PB.10007.2']
['PB.10008.11', 'PB.10008.12', 'PB.10008.13', 'PB.10008.14', 'PB.10008.15', 'PB.10008.2', 'PB.10008.5', 'PB.10008.7', 'PB.10008.9']
['PB.10008.1', 'PB.10008.4', 'PB.10008.6']
['PB.10008.10', 'PB.10008.8']
['PB.10008.3']
['PB.10009.1', 'PB.10009.10', 'PB.10009.12', 'PB.10009.15', 'PB.10009.2', 'PB.10009.3', 'PB.10009.4', 'PB.10009.5']
['PB.10009.13', 'PB.10009.7']
['PB.10009.11']
['PB.10009.14']
['PB.10009.6']
['PB.10009.8']
['PB.10009.9']
['PB.1001.1']
['PB.10010.1', 'PB.10010.6', 'PB.10010.7']
['PB.10010.10']
['PB.10010.11']
['PB.10010.2']
['PB.10010.3']
['PB.10010.4']
['PB.10010.5']
['PB.10010.8']
['PB.10010.9']
['PB.10011.1', 'PB.10011.3']
['PB.10011.2']
['PB.10012.1']
['PB.10012.2']
['PB.10013.1']
['PB.10014.1', 'PB.10014.2', 'PB.10014.3', 'PB.10014.4']
['PB.10014.5']
['PB.10014.6']
['PB.10015.3']
['PB.10016.1', 'PB.10016.2', 'PB.10016.3', 'PB.10016.4']
['PB.10016.5']
['PB.10017.1']
['PB.10017.2']
['PB.10017.3']
['PB.10018.1']
['PB.10019.1']
['PB.1002.1']
['PB.1002.2']
['PB.10020.1', 'PB.10020.2']
['PB.10021.1', 'PB.10021.2', 'PB.10021.3', 'PB.10021.4']
['PB.10021.5']
['PB.10021.6']
['PB.10021.7']
['PB.10022.1']
['PB.10023.1', 'PB.10023.13', 'PB.10023.14', 'PB.10023.15', 'PB.10023.16', 'PB.10023.2', 'PB.10023.5', 'PB.10023.7', 'PB.10023.8', 'PB.10023.9']
['PB.10023.11', 'PB.10023.20']
['PB.10023.18', 'PB.10023.4']
['PB.10023.10']
['PB.10023.12']
['PB.10023.17']
['PB.10023.19']
['PB.10023.3']
['PB.10023.6']
['PB.10024.1']
['PB.10025.1', 'PB.10025.13', 'PB.10025.6', 'PB.10025.8']
['PB.10025.14', 'PB.10025.3', 'PB.10025.7']
['PB.10025.11', 'PB.10025.4']
['PB.10025.10']
['PB.10025.12']
['PB.10025.15']
['PB.10025.2']
['PB.10025.5']
['PB.10025.9']
['PB.10026.11', 'PB.10026.12', 'PB.10026.13', 'PB.10026.15', 'PB.10026.17', 'PB.10026.2', 'PB.10026.20', 'PB.10026.21', 'PB.10026.23', 'PB.10026.3', 'PB.10026.4', 'PB.10026.5', 'PB.10026.6', 'PB.10026.9']
['PB.10026.1', 'PB.10026.10', 'PB.10026.8']
['PB.10026.19', 'PB.10026.7']
['PB.10026.14']
['PB.10026.16']
['PB.10026.18']
['PB.10026.22']
['PB.10027.1', 'PB.10027.2', 'PB.10027.3', 'PB.10027.4', 'PB.10027.5', 'PB.10027.6']
['PB.10027.7']
['PB.10028.11', 'PB.10028.3', 'PB.10028.9']
['PB.10028.12', 'PB.10028.20', 'PB.10028.4']
['PB.10028.13', 'PB.10028.22', 'PB.10028.6']
['PB.10028.15', 'PB.10028.7']
['PB.10028.1']
['PB.10028.2']
['PB.10028.5']
['PB.10028.25']
['PB.10028.24']
['PB.10028.23']
['PB.10028.21']
['PB.10028.18']
['PB.10028.19']
['PB.10028.10']
['PB.10028.17']
['PB.10028.16']
['PB.10028.14']
['PB.10028.8']
['PB.10029.1', 'PB.10029.10', 'PB.10029.101', 'PB.10029.102', 'PB.10029.11', 'PB.10029.18', 'PB.10029.20', 'PB.10029.22', 'PB.10029.28', 'PB.10029.3', 'PB.10029.34', 'PB.10029.35', 'PB.10029.37', 'PB.10029.41', 'PB.10029.46', 'PB.10029.49', 'PB.10029.52', 'PB.10029.56', 'PB.10029.57', 'PB.10029.60', 'PB.10029.63', 'PB.10029.64', 'PB.10029.68', 'PB.10029.69', 'PB.10029.70', 'PB.10029.71', 'PB.10029.73', 'PB.10029.81', 'PB.10029.84', 'PB.10029.87', 'PB.10029.93', 'PB.10029.94', 'PB.10029.97', 'PB.10029.99']
['PB.10029.109', 'PB.10029.110', 'PB.10029.111', 'PB.10029.112', 'PB.10029.113', 'PB.10029.114', 'PB.10029.115', 'PB.10029.116', 'PB.10029.117', 'PB.10029.118', 'PB.10029.15', 'PB.10029.21', 'PB.10029.30', 'PB.10029.36', 'PB.10029.38', 'PB.10029.39', 'PB.10029.51', 'PB.10029.79', 'PB.10029.89', 'PB.10029.96']
['PB.10029.17', 'PB.10029.24', 'PB.10029.25', 'PB.10029.29', 'PB.10029.33', 'PB.10029.4', 'PB.10029.45', 'PB.10029.54', 'PB.10029.6', 'PB.10029.7', 'PB.10029.75', 'PB.10029.76', 'PB.10029.77', 'PB.10029.95']
['PB.10029.103', 'PB.10029.106', 'PB.10029.107', 'PB.10029.48']
['PB.10029.13', 'PB.10029.8']
['PB.10029.5', 'PB.10029.72']
['PB.10029.104', 'PB.10029.108']
['PB.10029.12']
['PB.10029.82']
['PB.10029.61']
['PB.10029.65']
['PB.10029.66']
['PB.10029.67']
['PB.10029.74']
['PB.10029.78']
['PB.10029.80']
['PB.10029.83']
['PB.10029.58']
['PB.10029.85']
['PB.10029.86']
['PB.10029.88']
['PB.10029.9']
['PB.10029.90']
['PB.10029.91']
['PB.10029.92']
['PB.10029.59']
['PB.10029.55']
['PB.10029.105']
['PB.10029.31']
['PB.10029.14']
['PB.10029.16']
['PB.10029.19']
['PB.10029.2']
['PB.10029.23']
['PB.10029.26']
['PB.10029.27']
['PB.10029.32']
['PB.10029.53']
['PB.10029.40']
['PB.10029.42']
['PB.10029.43']
['PB.10029.44']
['PB.10029.47']
['PB.10029.100']
['PB.10029.50']
['PB.10029.98']
['PB.1003.1', 'PB.1003.100', 'PB.1003.13', 'PB.1003.2', 'PB.1003.22', 'PB.1003.23', 'PB.1003.24', 'PB.1003.26', 'PB.1003.30', 'PB.1003.35', 'PB.1003.36', 'PB.1003.42', 'PB.1003.51', 'PB.1003.52', 'PB.1003.57', 'PB.1003.58', 'PB.1003.59', 'PB.1003.60', 'PB.1003.62', 'PB.1003.72', 'PB.1003.73', 'PB.1003.74', 'PB.1003.76', 'PB.1003.8', 'PB.1003.83', 'PB.1003.88', 'PB.1003.9', 'PB.1003.91', 'PB.1003.92', 'PB.1003.95', 'PB.1003.96', 'PB.1003.98']
['PB.1003.32', 'PB.1003.44', 'PB.1003.64', 'PB.1003.79', 'PB.1003.80', 'PB.1003.89']
['PB.1003.115', 'PB.1003.116', 'PB.1003.117', 'PB.1003.119', 'PB.1003.120']
['PB.1003.48', 'PB.1003.70', 'PB.1003.75', 'PB.1003.82', 'PB.1003.94']
['PB.1003.18', 'PB.1003.25', 'PB.1003.31', 'PB.1003.34', 'PB.1003.90']
['PB.1003.105', 'PB.1003.107', 'PB.1003.109', 'PB.1003.113']
['PB.1003.37', 'PB.1003.38', 'PB.1003.54']
['PB.1003.41', 'PB.1003.5', 'PB.1003.53']
['PB.1003.10', 'PB.1003.14']
['PB.1003.121', 'PB.1003.122']
['PB.1003.50', 'PB.1003.77']
['PB.1003.84']
['PB.1003.6']
['PB.1003.45']
['PB.1003.46']
['PB.1003.97']
['PB.1003.47']
['PB.1003.93']
['PB.1003.87']
['PB.1003.49']
['PB.1003.55']
['PB.1003.56']
['PB.1003.61']
['PB.1003.81']
['PB.1003.86']
['PB.1003.63']
['PB.1003.65']
['PB.1003.43']
['PB.1003.67']
['PB.1003.68']
['PB.1003.85']
['PB.1003.69']
['PB.1003.7']
['PB.1003.71']
['PB.1003.78']
['PB.1003.66']
['PB.1003.39']
['PB.1003.40']
['PB.1003.118']
['PB.1003.101']
['PB.1003.102']
['PB.1003.103']
['PB.1003.104']
['PB.1003.106']
['PB.1003.108']
['PB.1003.11']
['PB.1003.110']
['PB.1003.111']
['PB.1003.112']
['PB.1003.114']
['PB.1003.12']
['PB.1003.4']
['PB.1003.15']
['PB.1003.16']
['PB.1003.17']
['PB.1003.19']
['PB.1003.20']
['PB.1003.21']
['PB.1003.27']
['PB.1003.28']
['PB.1003.29']
['PB.1003.3']
['PB.1003.33']
['PB.1003.99']
['PB.10030.4']
['PB.10031.1', 'PB.10031.11', 'PB.10031.12', 'PB.10031.13', 'PB.10031.14', 'PB.10031.15', 'PB.10031.18', 'PB.10031.2', 'PB.10031.20', 'PB.10031.21', 'PB.10031.22', 'PB.10031.24', 'PB.10031.28', 'PB.10031.3', 'PB.10031.32', 'PB.10031.33', 'PB.10031.34', 'PB.10031.35', 'PB.10031.6', 'PB.10031.9']
['PB.10031.44', 'PB.10031.45', 'PB.10031.46', 'PB.10031.47']
['PB.10031.23', 'PB.10031.25', 'PB.10031.4']
['PB.10031.10', 'PB.10031.17']
['PB.10031.38']
['PB.10031.7']
['PB.10031.5']
['PB.10031.43']
['PB.10031.42']
['PB.10031.41']
['PB.10031.40']
['PB.10031.39']
['PB.10031.37']
['PB.10031.36']
['PB.10031.31']
['PB.10031.30']
['PB.10031.29']
['PB.10031.27']
['PB.10031.26']
['PB.10031.19']
['PB.10031.16']
['PB.10031.8']
['PB.10032.1']
hi
['PB.10034.10', 'PB.10034.12', 'PB.10034.13', 'PB.10034.2', 'PB.10034.3', 'PB.10034.5', 'PB.10034.8', 'PB.10034.9']
['PB.10034.1']
['PB.10034.6']
['PB.10034.7']
hi
['PB.10036.1', 'PB.10036.10', 'PB.10036.3', 'PB.10036.4', 'PB.10036.5', 'PB.10036.6', 'PB.10036.7', 'PB.10036.8', 'PB.10036.9']
['PB.10036.2']
['PB.10037.1']
['PB.10038.1', 'PB.10038.10', 'PB.10038.11', 'PB.10038.12', 'PB.10038.14', 'PB.10038.15', 'PB.10038.2', 'PB.10038.20', 'PB.10038.22', 'PB.10038.25', 'PB.10038.27', 'PB.10038.3', 'PB.10038.30', 'PB.10038.31', 'PB.10038.34', 'PB.10038.35', 'PB.10038.36', 'PB.10038.37', 'PB.10038.39', 'PB.10038.40', 'PB.10038.42', 'PB.10038.6', 'PB.10038.7', 'PB.10038.8', 'PB.10038.9']
['PB.10038.17', 'PB.10038.45']
['PB.10038.38', 'PB.10038.43']
['PB.10038.29']
['PB.10038.46']
['PB.10038.44']
['PB.10038.41']
['PB.10038.4']
['PB.10038.33']
['PB.10038.32']
['PB.10038.28']
['PB.10038.13']
['PB.10038.26']
['PB.10038.24']
['PB.10038.23']
['PB.10038.21']
['PB.10038.19']
['PB.10038.18']
['PB.10038.16']
['PB.10038.5']
['PB.10039.1', 'PB.10039.13', 'PB.10039.14', 'PB.10039.16', 'PB.10039.17', 'PB.10039.19', 'PB.10039.2', 'PB.10039.21', 'PB.10039.22', 'PB.10039.23', 'PB.10039.24', 'PB.10039.3', 'PB.10039.5', 'PB.10039.6', 'PB.10039.7', 'PB.10039.8']
['PB.10039.10']
['PB.10039.11']
['PB.10039.12']
['PB.10039.15']
['PB.10039.18']
['PB.10039.20']
['PB.10039.25']
['PB.10039.4']
['PB.10039.9']
['PB.1004.1', 'PB.1004.10', 'PB.1004.13', 'PB.1004.14', 'PB.1004.2', 'PB.1004.3', 'PB.1004.4', 'PB.1004.5', 'PB.1004.6', 'PB.1004.7', 'PB.1004.8']
['PB.1004.11', 'PB.1004.16', 'PB.1004.17', 'PB.1004.19']
['PB.1004.12', 'PB.1004.21']
['PB.1004.15']
['PB.1004.18']
['PB.1004.20']
['PB.1004.9']
['PB.10040.11', 'PB.10040.13', 'PB.10040.15', 'PB.10040.19', 'PB.10040.2', 'PB.10040.20', 'PB.10040.22', 'PB.10040.23', 'PB.10040.27', 'PB.10040.28', 'PB.10040.29', 'PB.10040.32', 'PB.10040.4', 'PB.10040.5', 'PB.10040.7', 'PB.10040.8']
['PB.10040.10', 'PB.10040.14', 'PB.10040.21']
['PB.10040.33', 'PB.10040.34', 'PB.10040.35']
['PB.10040.25', 'PB.10040.26']
['PB.10040.1']
['PB.10040.12']
['PB.10040.16']
['PB.10040.17']
['PB.10040.18']
['PB.10040.24']
['PB.10040.3']
['PB.10040.30']
['PB.10040.31']
['PB.10040.6']
['PB.10040.9']
['PB.10041.10', 'PB.10041.12', 'PB.10041.15', 'PB.10041.2', 'PB.10041.3', 'PB.10041.4', 'PB.10041.5', 'PB.10041.8']
['PB.10041.16', 'PB.10041.7']
['PB.10041.1']
['PB.10041.11']
['PB.10041.13']
['PB.10041.14']
['PB.10041.6']
['PB.10041.9']
['PB.10042.10', 'PB.10042.12', 'PB.10042.13', 'PB.10042.18', 'PB.10042.21', 'PB.10042.22', 'PB.10042.23', 'PB.10042.24', 'PB.10042.25', 'PB.10042.27', 'PB.10042.29', 'PB.10042.34']
['PB.10042.1', 'PB.10042.2', 'PB.10042.3', 'PB.10042.4', 'PB.10042.6', 'PB.10042.7', 'PB.10042.8']
['PB.10042.14', 'PB.10042.15', 'PB.10042.16', 'PB.10042.26', 'PB.10042.30', 'PB.10042.31']
['PB.10042.17', 'PB.10042.35']
['PB.10042.11']
['PB.10042.19']
['PB.10042.20']
['PB.10042.28']
['PB.10042.32']
['PB.10042.33']
['PB.10042.5']
['PB.10042.9']
['PB.10042.10', 'PB.10042.12', 'PB.10042.13', 'PB.10042.18', 'PB.10042.21', 'PB.10042.22', 'PB.10042.23', 'PB.10042.24', 'PB.10042.25', 'PB.10042.27', 'PB.10042.29', 'PB.10042.34']
['PB.10042.1', 'PB.10042.2', 'PB.10042.3', 'PB.10042.4', 'PB.10042.6', 'PB.10042.7', 'PB.10042.8']
['PB.10042.14', 'PB.10042.15', 'PB.10042.16', 'PB.10042.26', 'PB.10042.30', 'PB.10042.31']
['PB.10042.17', 'PB.10042.35']
['PB.10042.11']
['PB.10042.19']
['PB.10042.20']
['PB.10042.28']
['PB.10042.32']
['PB.10042.33']
['PB.10042.5']
['PB.10042.9']
['PB.10043.10', 'PB.10043.12', 'PB.10043.16', 'PB.10043.17', 'PB.10043.2', 'PB.10043.20', 'PB.10043.21', 'PB.10043.22', 'PB.10043.31', 'PB.10043.33', 'PB.10043.37', 'PB.10043.40', 'PB.10043.45', 'PB.10043.46', 'PB.10043.47', 'PB.10043.50', 'PB.10043.7', 'PB.10043.8', 'PB.10043.9']
['PB.10043.13', 'PB.10043.18', 'PB.10043.24', 'PB.10043.3', 'PB.10043.48', 'PB.10043.49', 'PB.10043.51']
['PB.10043.23', 'PB.10043.26', 'PB.10043.28']
['PB.10043.36', 'PB.10043.41', 'PB.10043.44']
['PB.10043.1', 'PB.10043.39']
['PB.10043.35', 'PB.10043.43']
['PB.10043.34', 'PB.10043.42']
['PB.10043.32']
['PB.10043.52']
['PB.10043.5']
['PB.10043.4']
['PB.10043.38']
['PB.10043.29']
['PB.10043.30']
['PB.10043.27']
['PB.10043.25']
['PB.10043.19']
['PB.10043.15']
['PB.10043.14']
['PB.10043.11']
['PB.10043.6']
['PB.10044.1']
['PB.10044.2']
['PB.10045.1', 'PB.10045.2', 'PB.10045.3', 'PB.10045.4', 'PB.10045.5']
['PB.10046.1', 'PB.10046.16', 'PB.10046.17', 'PB.10046.2', 'PB.10046.22', 'PB.10046.24', 'PB.10046.26', 'PB.10046.3', 'PB.10046.31', 'PB.10046.42', 'PB.10046.48', 'PB.10046.51', 'PB.10046.55', 'PB.10046.57', 'PB.10046.58', 'PB.10046.60', 'PB.10046.61', 'PB.10046.7', 'PB.10046.9']
['PB.10046.35', 'PB.10046.47', 'PB.10046.49', 'PB.10046.6', 'PB.10046.70', 'PB.10046.76', 'PB.10046.77', 'PB.10046.78', 'PB.10046.79', 'PB.10046.80', 'PB.10046.82', 'PB.10046.84', 'PB.10046.85', 'PB.10046.86', 'PB.10046.87', 'PB.10046.88']
['PB.10046.63', 'PB.10046.64', 'PB.10046.65', 'PB.10046.66', 'PB.10046.67', 'PB.10046.68', 'PB.10046.69']
['PB.10046.10', 'PB.10046.28', 'PB.10046.43', 'PB.10046.46']
['PB.10046.37', 'PB.10046.92', 'PB.10046.93']
['PB.10046.54', 'PB.10046.72', 'PB.10046.73']
['PB.10046.90', 'PB.10046.91']
['PB.10046.14', 'PB.10046.33']
['PB.10046.15', 'PB.10046.34']
['PB.10046.23', 'PB.10046.8']
['PB.10046.44', 'PB.10046.53']
['PB.10046.56']
['PB.10046.5']
['PB.10046.50']
['PB.10046.52']
['PB.10046.71']
['PB.10046.59']
['PB.10046.62']
['PB.10046.74']
['PB.10046.75']
['PB.10046.81']
['PB.10046.83']
['PB.10046.89']
['PB.10046.94']
['PB.10046.45']
['PB.10046.4']
['PB.10046.41']
['PB.10046.40']
['PB.10046.11']
['PB.10046.12']
['PB.10046.13']
['PB.10046.18']
['PB.10046.19']
['PB.10046.20']
['PB.10046.21']
['PB.10046.25']
['PB.10046.27']
['PB.10046.29']
['PB.10046.30']
['PB.10046.32']
['PB.10046.36']
['PB.10046.38']
['PB.10046.39']
['PB.10046.95']
['PB.10047.1', 'PB.10047.2']
['PB.10048.1', 'PB.10048.3', 'PB.10048.4', 'PB.10048.6', 'PB.10048.8']
['PB.10048.10', 'PB.10048.9']
['PB.10048.2']
['PB.10048.5']
['PB.10048.7']
['PB.10049.2', 'PB.10049.3', 'PB.10049.4', 'PB.10049.5', 'PB.10049.7']
['PB.10049.1']
['PB.10049.6']
['PB.1005.1', 'PB.1005.2']
['PB.10050.1', 'PB.10050.12', 'PB.10050.13', 'PB.10050.3', 'PB.10050.4', 'PB.10050.6', 'PB.10050.7', 'PB.10050.9']
['PB.10050.15', 'PB.10050.17', 'PB.10050.5']
['PB.10050.11', 'PB.10050.14']
['PB.10050.10']
['PB.10050.16']
['PB.10050.2']
['PB.10050.8']
['PB.10051.1', 'PB.10051.2']
['PB.10052.1']
['PB.10052.2']
['PB.10053.1']
['PB.10053.2']
['PB.10054.1']
['PB.10055.10', 'PB.10055.11', 'PB.10055.15', 'PB.10055.17', 'PB.10055.23', 'PB.10055.24', 'PB.10055.27', 'PB.10055.28', 'PB.10055.29', 'PB.10055.3', 'PB.10055.30', 'PB.10055.31', 'PB.10055.32', 'PB.10055.34', 'PB.10055.37', 'PB.10055.38', 'PB.10055.43', 'PB.10055.45', 'PB.10055.46', 'PB.10055.48', 'PB.10055.49', 'PB.10055.5', 'PB.10055.51', 'PB.10055.57', 'PB.10055.58', 'PB.10055.59', 'PB.10055.6', 'PB.10055.7', 'PB.10055.8']
['PB.10055.1', 'PB.10055.12', 'PB.10055.20', 'PB.10055.25', 'PB.10055.39']
['PB.10055.14', 'PB.10055.33', 'PB.10055.53', 'PB.10055.56']
['PB.10055.13', 'PB.10055.44']
['PB.10055.47', 'PB.10055.55']
['PB.10055.4']
['PB.10055.54']
['PB.10055.52']
['PB.10055.50']
['PB.10055.42']
['PB.10055.41']
['PB.10055.40']
['PB.10055.35']
['PB.10055.36']
['PB.10055.26']
['PB.10055.22']
['PB.10055.21']
['PB.10055.2']
['PB.10055.19']
['PB.10055.18']
['PB.10055.16']
['PB.10055.9']
['PB.10056.1']
hi
['PB.10058.1', 'PB.10058.2', 'PB.10058.3']
['PB.10059.1']
['PB.1006.10', 'PB.1006.2', 'PB.1006.3', 'PB.1006.4', 'PB.1006.5', 'PB.1006.9']
['PB.1006.1']
['PB.1006.6']
['PB.1006.7']
['PB.1006.8']
['PB.10060.14', 'PB.10060.16', 'PB.10060.18']
['PB.10060.29', 'PB.10060.31']
['PB.10060.33', 'PB.10060.34']
['PB.10060.35', 'PB.10060.36']
['PB.10060.37', 'PB.10060.38']
['PB.10060.15', 'PB.10060.5']
['PB.10060.41', 'PB.10060.7']
['PB.10060.42']
['PB.10060.39']
['PB.10060.4']
['PB.10060.40']
['PB.10060.43']
['PB.10060.30']
['PB.10060.44']
['PB.10060.45']
['PB.10060.46']
['PB.10060.47']
['PB.10060.6']
['PB.10060.8']
['PB.10060.32']
['PB.10060.1']
['PB.10060.3']
['PB.10060.10']
['PB.10060.11']
['PB.10060.12']
['PB.10060.13']
['PB.10060.17']
['PB.10060.19']
['PB.10060.2']
['PB.10060.20']
['PB.10060.21']
['PB.10060.22']
['PB.10060.23']
['PB.10060.24']
['PB.10060.25']
['PB.10060.26']
['PB.10060.27']
['PB.10060.28']
['PB.10060.9']
['PB.10061.1']
['PB.10061.2']
hi
['PB.10063.3', 'PB.10063.4', 'PB.10063.5']
['PB.10063.1']
['PB.10063.2']
['PB.10063.6']
['PB.10064.1', 'PB.10064.2', 'PB.10064.3', 'PB.10064.4', 'PB.10064.5', 'PB.10064.6']
['PB.10064.7']
['PB.10065.1', 'PB.10065.2']
['PB.10066.1']
['PB.10067.2', 'PB.10067.3']
['PB.10067.6', 'PB.10067.7']
['PB.10067.1']
['PB.10067.4']
['PB.10067.5']
hi
['PB.10069.1']
['PB.1007.1', 'PB.1007.2']
['PB.1007.3']
['PB.10070.1']
['PB.10070.2']
['PB.10070.3']
['PB.10070.4']
['PB.10070.5']
['PB.10070.6']
['PB.10070.7']
['PB.10071.11', 'PB.10071.12', 'PB.10071.14', 'PB.10071.17', 'PB.10071.18', 'PB.10071.2', 'PB.10071.6', 'PB.10071.8']
['PB.10071.1']
['PB.10071.10']
['PB.10071.13']
['PB.10071.15']
['PB.10071.16']
['PB.10071.3']
['PB.10071.4']
['PB.10071.5']
['PB.10071.7']
['PB.10071.9']
['PB.10072.1', 'PB.10072.10', 'PB.10072.11', 'PB.10072.3', 'PB.10072.4', 'PB.10072.5', 'PB.10072.6', 'PB.10072.7', 'PB.10072.8', 'PB.10072.9']
['PB.10072.12']
['PB.10072.2']
['PB.10073.1', 'PB.10073.2', 'PB.10073.5', 'PB.10073.6']
['PB.10073.3']
['PB.10073.7']
['PB.10074.12', 'PB.10074.14', 'PB.10074.16', 'PB.10074.2', 'PB.10074.3', 'PB.10074.4', 'PB.10074.7', 'PB.10074.8']
['PB.10074.1', 'PB.10074.6']
['PB.10074.10']
['PB.10074.11']
['PB.10074.13']
['PB.10074.15']
['PB.10074.17']
['PB.10074.18']
['PB.10074.5']
['PB.10074.9']
['PB.10075.10', 'PB.10075.11', 'PB.10075.2', 'PB.10075.3', 'PB.10075.4', 'PB.10075.5', 'PB.10075.7', 'PB.10075.9']
['PB.10075.1']
['PB.10075.6']
['PB.10075.8']
['PB.10076.12', 'PB.10076.13', 'PB.10076.14', 'PB.10076.16', 'PB.10076.17', 'PB.10076.18', 'PB.10076.2']
['PB.10076.1', 'PB.10076.3', 'PB.10076.4', 'PB.10076.6']
['PB.10076.10']
['PB.10076.15']
['PB.10076.5']
['PB.10076.7']
['PB.10076.8']
['PB.10076.9']
['PB.10076.12', 'PB.10076.13', 'PB.10076.14', 'PB.10076.16', 'PB.10076.17', 'PB.10076.18', 'PB.10076.2']

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

# TAMA

In [97]:
# full df
aug_ref=pd.read_pickle("tama_augustus_sqanti_full.pkl")
aug_map=aug_ref[["accession","gene","associated_gene","isoform"]]

out_df=pd.DataFrame()
for acc in aug_map["accession"].unique().tolist():
    acc_df=aug_map.loc[aug_map["accession"] == acc]
    acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
    out_df=pd.concat([out_df, acc_df])
    
# split by clear cases and different ones
clear = out_df.loc[out_df["association"] == 1]
unclear = out_df.loc[out_df["association"] != 1]

clear=clear.drop(labels="isoform", axis=1).drop_duplicates()

# associate gene type
IDs = augustus_refs(clear)

/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()
/tmp/ipykernel_125067/2085959111.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  acc_df["association"] = acc_df["associated_gene"].str.split("_").str.len().copy()

In [99]:
#relate refgenes and type
final=pd.DataFrame()
for i in ID["accession"].unique().tolist():
    acc_df=pd.DataFrame()
    acc_id=ID.loc[ID["accession"]==i]
    at=pd.read_pickle(f"sqanti/{i}_tama_augustus_sqanti_orf.pkl")
    at_type=pd.merge(left=at, right=acc_id[["gene","accession","associated_gene","type"]], how='left', left_on='Gene', right_on='gene').drop(labels="gene", axis=1)
    final=pd.concat([final,at_type])

In [103]:
final["read_support_sum"] = final["Read_Support_ORF"].apply(sum)

In [139]:
# Luisa helper
helper=pd.read_csv("luisa_helper_nlr.txt", header=None, names=["acc_gene"])
ID = pd.DataFrame()
ID["accession"] = helper["acc_gene"].str.split("_").str[0]
ID["gene"] = helper["acc_gene"].str.split("_").str[1]

In [140]:
ID["accession"].value_counts().sort_index()

at6137    6
at6923    7
at6929    7
at7143    6
at8285    7
at9104    7
at9336    7
at9503    7
at9578    6
at9744    7
at9762    5
at9806    7
at9830    6
at9847    7
at9852    7
at9879    6
at9883    7
at9900    7
Name: accession, dtype: int64

In [141]:
ID["accession"].unique().tolist()[1:]

['at6923',
 'at6929',
 'at7143',
 'at8285',
 'at9104',
 'at9336',
 'at9503',
 'at9578',
 'at9744',
 'at9762',
 'at9806',
 'at9830',
 'at9847',
 'at9852',
 'at9879',
 'at9883',
 'at9900']

In [142]:
final

,Gene,n ORFs,n Isoforms,Sqanti ORFs,Isoforms,n_Isoforms_ORF,Subcategories,Read_Support,Read_Support_ORF,accession,associated_gene,type,read_support_sum
0,G1,1,2,[MEDQVGFGFRPNDEELVGHYLRNKIEGNTSRDVEVAISEVNICSY...,"[[G1.1, G1.2]]",[2],"[[alternative_3end5end, alternative_3end5end]]","[[1, 1]]",[2],at6923,g1,NaN,2
1,G10,5,22,[MATAFAPTKLTATVPLHGSQENRLLLPIRLAPPSSFLGSTRSLSL...,"[[G10.1, G10.11, G10.13, G10.17, G10.18, G10.1...","[15, 3, 2, 1, 1]","[[alternative_3end5end, alternative_3end, alte...","[[3, 2, 54, 3, 1, 17, 41, 11, 1, 1, 18, 1, 1, ...","[175, 3, 2, 1, 1]",at6923,g9,NaN,182
2,G100,1,3,[MNKNQTVGLDSEDDDSDDYDIAQVNCELALVEGQLCNIPYELYDL...,"[[G100.1, G100.2, G100.3]]",[3],"[[multi-exon, multi-exon, multi-exon]]","[[2, 1, 1]]",[4],at6923,g131,NaN,4
3,G1000,4,12,[MVSQIISCLSQSSSLLCLSDSRRLILPKTCTCGGLSRFSPGFASR...,"[[G1000.1, G1000.11, G1000.2, G1000.3, G1000.6...","[7, 2, 2, 1]","[[alternative_3end, alternative_3end, alternat...","[[1, 8, 1, 1, 1, 2, 1], [1, 1], [1, 1], [1]]","[15, 2, 2, 1]",at6923,g1385,NaN,20
4,G10000,2,8,[MDTVNDSFSPGSSRPSPATLSREDCWSEEATFTLIQAWGNRYVDL...,"[[G10000.1, G10000.3, G10000.4, G10000.5, G100...","[5, 3]","[[multi-exon, multi-exon, multi-exon, multi-ex...","[[1, 1, 1, 3, 1], [1, 1, 1]]","[7, 3]",at6923,g19407,NaN,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16622,G9995,8,39,[MNFGSLFDNTPGGGSTGARLLSGLSYGNHTAATNVLPGGAMAQAA...,"[[G9995.1, G9995.11, G9995.12, G9995.13, G9995...","[20, 5, 4, 3, 3, 2, 1, 1]","[[alternative_3end, alternative_5end, referenc...","[[1, 2, 1, 2, 1, 3, 5, 1, 3, 2, 7, 1, 1, 1, 1,...","[41, 5, 4, 3, 3, 2, 1, 1]",col0,AT4G00730,NaN,60
16623,G9996,4,34,[MGHVNLPASKRGNPRQWRLLDIVTAAFFGIVLLFFILLFTPLGDS...,"[[G9996.1, G9996.10, G9996.11, G9996.12, G9996...","[31, 1, 1, 1]","[[at_least_one_novel_splicesite, alternative_5...","[[1, 1, 1, 1, 1, 1, 6, 2, 1, 1, 2, 1, 1, 1, 1,...","[57, 1, 1, 1]",col0,AT4G00740,NaN,60
16624,G9997,3,6,[MGNYRWPSKLSKLSLRAKQTNLYRVILIAILCVTFYFVGVWQHSG...,"[[G9997.1, G9997.3, G9997.4, G9997.5], [G9997....","[4, 1, 1]","[[reference_match, alternative_3end, reference...","[[3, 1, 1, 1], [1], [1]]","[6, 1, 1]",col0,AT4G00750,NaN,8
16625,G9998,2,6,[MVSPTRDAIQSYMSITGASESLAIQRLEEHGNNLPEAINAHFRDV...,"[[G9998.1, G9998.2, G9998.3, G9998.4, G9998.5]...","[5, 1]","[[reference_match, reference_match, alternativ...","[[1, 1, 1, 1, 3], [1]]","[7, 1]",col0,AT4G00752,busco,8
16626,G9999,2,12,[MDFVNNLDTDTSLSILSCLDDPSDIVRASAVSRSWRQFVVKYSLS...,"[[G9999.1, G9999.10, G9999.11, G9999.12, G9999...","[11, 1]","[[reference_match, alternative_3end, reference...","[[2, 1, 1, 2, 2, 1, 1, 1, 3, 2, 1], [1]]","[17, 1]",col0,AT4G00755,NaN,18

In [143]:
out=pd.DataFrame()
for i in ID["accession"].unique().tolist():
    acc_df=pd.DataFrame()
    acc_gene=ID.loc[ID["accession"]==i]
    acc_final=final.loc[final["accession"]==i]
    at_nlr=acc_final[acc_final["associated_gene"].isin(acc_gene["gene"])]
    out=pd.concat([out,at_nlr])

In [144]:
out["accession"].value_counts().sort_index()

at6923    7
at6929    6
at7143    6
at8285    6
at9104    7
at9336    5
at9503    6
at9578    6
at9744    7
at9762    5
at9806    7
at9830    5
at9847    6
at9852    7
at9879    6
at9883    7
at9900    7
Name: accession, dtype: int64

In [145]:
x=out[["accession", "Gene","associated_gene","n Isoforms", "read_support_sum"]]

In [146]:
x

      accession    Gene associated_gene  n Isoforms  read_support_sum
2724     at6923  G12377          g24288          28               107
3618     at6923  G13159          g25379          36               108
7677     at6923  G16726          g32065          17                18
7698     at6923  G16745          g32097          23                29
7699     at6923  G16746          g32098          22                27
...         ...     ...             ...         ...               ...
7516     at9900  G16648          g31656          10                10
7540     at9900  G16669          g31688          18                19
7543     at9900  G16671          g31689          13                15
8181     at9900   G2157           g3277           2                 3
14068    at9900   G7368          g13676           9                13

[106 rows x 5 columns]

In [147]:
x.to_csv("helper_nlr_read_support.csv", index=False)