In [1]:
import pandas as pd
from tqdm import tqdm
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import glob

In [13]:
gff = pd.read_csv("../output/v2/collapse_tama/at9900.collapsed.tama.v2.gff3")

In [14]:
gff

                                           ##gff-version 3
0                                        # gffread v0.12.7
1        # gffread -E --keep-genes output/v2/collapse_t...
2        at9900_1_chr1\tblank\tgene\t7375\t9620\t.\t+\t...
3        at9900_1_chr1\tblank\ttranscript\t7375\t9620\t...
4        at9900_1_chr1\tblank\texon\t7375\t7657\t.\t+\t...
...                                                    ...
1685665  at9900_9_u178\tblank\ttranscript\t95893\t98489...
1685666  at9900_9_u178\tblank\texon\t95893\t96294\t.\t-...
1685667  at9900_9_u178\tblank\texon\t96926\t97063\t.\t-...
1685668  at9900_9_u178\tblank\texon\t97716\t97873\t.\t-...
1685669  at9900_9_u178\tblank\texon\t98323\t98489\t.\t-...

[1685670 rows x 1 columns]

In [18]:
gff = pd.read_csv("../output/v2/collapse_tama/at9900.collapsed.tama.v2.gff3", sep="\t", skiprows=2, index_col=False)

/tmp/ipykernel_54584/3972028769.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  gff = pd.read_csv("../output/v2/collapse_tama/at9900.collapsed.tama.v2.gff3", sep="\t", skiprows=2, index_col=False)

In [19]:
gff

        # gffread -E --keep-genes output/v2/collapse_tama/at9900.collapsed.tama.v2.gtf -o output/v2/collapse_tama/at9900.collapsed.tama.v2.gff3
0                                            at9900_1_chr1
1                                            at9900_1_chr1
2                                            at9900_1_chr1
3                                            at9900_1_chr1
4                                            at9900_1_chr1
...                                                    ...
1685663                                      at9900_9_u178
1685664                                      at9900_9_u178
1685665                                      at9900_9_u178
1685666                                      at9900_9_u178
1685667                                      at9900_9_u178

[1685668 rows x 1 columns]